version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=admin
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - app-network

  backend:
    build:
      context: ./api/BookLibraryApi
    container_name: book-store-back
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    networks:
      - app-network

  frontend:
    build:
      context: ./front
    container_name: book-store-front
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge